# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AarDropdown',
            fields=[
                ('sno', models.AutoField(db_column='Sno', primary_key=True, serialize=False)),
                ('pid', models.IntegerField(blank=True, db_column='Pid', null=True)),
                ('field', models.CharField(blank=True, db_column='Field', max_length=500, null=True)),
                ('value', models.CharField(blank=True, db_column='Value', max_length=500, null=True)),
                ('marks', models.IntegerField(blank=True, db_column='Marks', null=True)),
            ],
            options={
                'db_table': 'aar_dropdown',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(db_column='Author', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher_type',
            field=models.ForeignKey(db_column='Publisher_Type', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher_type', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='books',
            name='role',
            field=models.ForeignKey(db_column='Role', default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='role', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='books',
            name='role_for',
            field=models.ForeignKey(db_column='Role_For', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchconference',
            name='author',
            field=models.ForeignKey(db_column='Author', on_delete=django.db.models.deletion.CASCADE, related_name='Author_Conference', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchconference',
            name='category',
            field=models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, related_name='Category_Research', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchconference',
            name='sub_category',
            field=models.ForeignKey(db_column='Sub_Category', on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Category_Conference', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchconference',
            name='type_of_conference',
            field=models.ForeignKey(db_column='Type_Of_Conference', on_delete=django.db.models.deletion.CASCADE, related_name='Conference_Type', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchguidence',
            name='course',
            field=models.ForeignKey(blank=True, db_column='Course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Course_Guidence', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchguidence',
            name='degree',
            field=models.ForeignKey(blank=True, db_column='Degree', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Degree', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchguidence',
            name='guidence',
            field=models.ForeignKey(db_column='Guidence', on_delete=django.db.models.deletion.CASCADE, related_name='Guidence', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchguidence',
            name='status',
            field=models.ForeignKey(blank=True, db_column='Status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Status', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchjournal',
            name='author',
            field=models.ForeignKey(db_column='Author', on_delete=django.db.models.deletion.CASCADE, related_name='Author_Journal', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchjournal',
            name='category',
            field=models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, related_name='Category_Journal', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchjournal',
            name='sub_category',
            field=models.ForeignKey(db_column='Sub_Category', on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Category_Journal', to='aar.AarDropdown'),
        ),
        migrations.AlterField(
            model_name='researchjournal',
            name='type_of_journal',
            field=models.ForeignKey(db_column='Type_Of_Journal', on_delete=django.db.models.deletion.CASCADE, related_name='Type_Of_Journal', to='aar.AarDropdown'),
        ),
    ]
