# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aar', '0003_auto_20171204_1411'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDropdown',
            new_name='AarDropdown',
        ),
        migrations.AlterModelTable(
            name='aardropdown',
            table='aar_dropdown',
        ),
    ]
