# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aar', '0004_auto_20171204_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AarDropdown',
        ),
    ]
