# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aar', '0005_delete_aardropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='approve_status',
            field=models.CharField(db_column='book_status', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchconference',
            name='approve_status',
            field=models.CharField(db_column='conf_status', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchguidence',
            name='approve_status',
            field=models.CharField(db_column='guid_status', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchjournal',
            name='approve_status',
            field=models.CharField(db_column='jour_status', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
